version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2022-06-02T02-11-04Z.fips
    container_name: minio
    command: "server --console-address=0.0.0.0:19000 --address=0.0.0.0:19001 /data "
    ports:
      - 127.0.0.1:19001:19001
      - 19000:19000
    volumes:
      - minio-data:/data
    restart: always
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "miniostorage"
  
volumes:
  minio-data:
