From ubuntu:22.04

RUN apt-get update
RUN apt-get install -y ca-certificates
RUN apt-get install -y wget
#RUN apt-get install -y jq
RUN wget https://github.com/helium/helium-wallet-rs/releases/download/v2.0.0-rc.4/helium-wallet-x86-64-linux.tar.gz  && \
    tar -zxvf helium-wallet-x86-64-linux.tar.gz && \
    rm -f helium-wallet-x86-64-linux.tar.gz && \
    cp helium-wallet-x86-64-linux/helium-wallet /usr/bin/helium-wallet && \
    chmod ugo+x /usr/bin/helium-wallet
CMD ["/bin/sh", "-c","while true; do sleep 1; done"]



