From ubuntu:22.04

RUN apt-get update
RUN apt-get install -y ca-certificates
RUN apt-get install -y jq
RUN apt-get install -y expect
RUN apt-get install -y \
    make \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    libgdbm-dev \
    libnss3-dev \
    libedit-dev \
    libc6-dev \
    gcc-10 \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

# 下载 Python 3.6.8 源码包
RUN wget https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tgz

# 解压缩源码包
RUN tar -xzf Python-3.6.8.tgz

# 进入 Python 源码目录
WORKDIR /home

# 配置并编译 Python
RUN CC="gcc-10" ./configure --enable-optimizations --with-lto --with-pydebug
RUN make altinstall

# 设置环境变量
ENV PATH="/usr/local/bin:${PATH}"

# 升级 pip
RUN python3.6 -m pip install --upgrade pip

# 安装 scikit-build、Cython 和 CMake
RUN python3.6 -m pip install scikit-build cython cmake

# 验证 Python 安装
RUN python3.6 --version
RUN python3.6 -m pip install h3==3.7.7
RUN wget https://github.com/helium/helium-wallet-rs/releases/download/v2.0.0-rc.4/helium-wallet-x86-64-linux.tar.gz  && \
    tar -zxvf helium-wallet-x86-64-linux.tar.gz && \
    rm -f helium-wallet-x86-64-linux.tar.gz && \
    cp helium-wallet-x86-64-linux/helium-wallet /usr/bin/helium-wallet && \
    chmod ugo+x /usr/bin/helium-wallet
COPY get_coordinates.py /etc/helium/get_coordinates.py
COPY start.sh /usr/local/bin/start.sh
CMD ["/bin/sh", "-c","while true; do sleep 1; done"]



